# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_input.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(917, 720)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setIconSize(QtCore.QSize(50, 50))
        self.tabWidget.setObjectName("tabWidget")
        self.input_tab = QtWidgets.QWidget()
        self.input_tab.setObjectName("input_tab")
        self.layoutWidget = QtWidgets.QWidget(self.input_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 30, 581, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_label = QtWidgets.QLabel(self.layoutWidget)
        self.input_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.input_label.setObjectName("input_label")
        self.verticalLayout.addWidget(self.input_label)
        self.input_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_lineEdit.setText("")
        self.input_lineEdit.setObjectName("input_lineEdit")
        self.verticalLayout.addWidget(self.input_lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_push = QtWidgets.QPushButton(self.layoutWidget)
        self.file_push.setObjectName("file_push")
        self.horizontalLayout.addWidget(self.file_push)
        self.filename_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.filename_lineEdit.setText("")
        self.filename_lineEdit.setObjectName("filename_lineEdit")
        self.horizontalLayout.addWidget(self.filename_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.user_label = QtWidgets.QLabel(self.layoutWidget)
        self.user_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.user_label.setObjectName("user_label")
        self.verticalLayout.addWidget(self.user_label)
        self.username_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.username_lineEdit.setText("")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout.addWidget(self.username_lineEdit)
        self.userinfo_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.userinfo_lineEdit.setText("")
        self.userinfo_lineEdit.setObjectName("userinfo_lineEdit")
        self.verticalLayout.addWidget(self.userinfo_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.analysis_label = QtWidgets.QLabel(self.layoutWidget)
        self.analysis_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.analysis_label.setObjectName("analysis_label")
        self.verticalLayout.addWidget(self.analysis_label)
        self.analysis_combobox = QtWidgets.QComboBox(self.layoutWidget)
        self.analysis_combobox.setObjectName("analysis_combobox")
        self.analysis_combobox.addItem("")
        self.analysis_combobox.addItem("")
        self.analysis_combobox.addItem("")
        self.verticalLayout.addWidget(self.analysis_combobox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.next_push = QtWidgets.QPushButton(self.layoutWidget)
        self.next_push.setObjectName("next_push")
        self.verticalLayout.addWidget(self.next_push)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.input_tab, icon, "")
        self.data_preprocess_tab_1 = QtWidgets.QWidget()
        self.data_preprocess_tab_1.setObjectName("data_preprocess_tab_1")
        self.layoutWidget1 = QtWidgets.QWidget(self.data_preprocess_tab_1)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 110, 601, 271))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.data_preprocess_label_1 = QtWidgets.QLabel(self.layoutWidget1)
        self.data_preprocess_label_1.setObjectName("data_preprocess_label_1")
        self.verticalLayout_4.addWidget(self.data_preprocess_label_1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.Incomplete_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Incomplete_checkbox.setObjectName("Incomplete_checkbox")
        self.verticalLayout_4.addWidget(self.Incomplete_checkbox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_end_label = QtWidgets.QLabel(self.layoutWidget1)
        self.start_end_label.setObjectName("start_end_label")
        self.horizontalLayout_2.addWidget(self.start_end_label)
        self.start_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.start_lineEdit.setText("")
        self.start_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.start_lineEdit.setObjectName("start_lineEdit")
        self.horizontalLayout_2.addWidget(self.start_lineEdit)
        self.end_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.end_lineEdit.setText("")
        self.end_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.end_lineEdit.setObjectName("end_lineEdit")
        self.horizontalLayout_2.addWidget(self.end_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.minimum_wafer_checkbox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.minimum_wafer_checkbox.setObjectName("minimum_wafer_checkbox")
        self.verticalLayout_4.addWidget(self.minimum_wafer_checkbox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.max_label = QtWidgets.QLabel(self.layoutWidget1)
        self.max_label.setObjectName("max_label")
        self.horizontalLayout_3.addWidget(self.max_label)
        self.min_num_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.min_num_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.min_num_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.min_num_lineEdit.setObjectName("min_num_lineEdit")
        self.horizontalLayout_3.addWidget(self.min_num_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.next_push_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.next_push_2.setObjectName("next_push_2")
        self.verticalLayout_4.addWidget(self.next_push_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/data_preprocess.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.data_preprocess_tab_1, icon1, "")
        self.data_preprocess2_tab = QtWidgets.QWidget()
        self.data_preprocess2_tab.setObjectName("data_preprocess2_tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.data_preprocess2_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(60, 80, 601, 281))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.data_preprocess_label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.data_preprocess_label_2.setObjectName("data_preprocess_label_2")
        self.verticalLayout_5.addWidget(self.data_preprocess_label_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.start_end_optimal_period_check = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.start_end_optimal_period_check.setObjectName("start_end_optimal_period_check")
        self.horizontalLayout_7.addWidget(self.start_end_optimal_period_check)
        self.start_end_optimal_period_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.start_end_optimal_period_label.setText("")
        self.start_end_optimal_period_label.setObjectName("start_end_optimal_period_label")
        self.horizontalLayout_7.addWidget(self.start_end_optimal_period_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.step_criterion_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.step_criterion_label.setObjectName("step_criterion_label")
        self.horizontalLayout_21.addWidget(self.step_criterion_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.step_criterion_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.step_criterion_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.step_criterion_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.step_criterion_lineEdit.setPlaceholderText("")
        self.step_criterion_lineEdit.setObjectName("step_criterion_lineEdit")
        self.horizontalLayout_21.addWidget(self.step_criterion_lineEdit)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_21.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.period_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.period_checkbox.setObjectName("period_checkbox")
        self.horizontalLayout_8.addWidget(self.period_checkbox)
        self.period_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.period_lineEdit.setObjectName("period_lineEdit")
        self.horizontalLayout_8.addWidget(self.period_lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.main_checkbox = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.main_checkbox.setObjectName("main_checkbox")
        self.horizontalLayout_9.addWidget(self.main_checkbox)
        self.main_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.main_lineEdit.setObjectName("main_lineEdit")
        self.horizontalLayout_9.addWidget(self.main_lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem11)
        self.next_push_3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.next_push_3.setObjectName("next_push_3")
        self.verticalLayout_5.addWidget(self.next_push_3)
        self.tabWidget.addTab(self.data_preprocess2_tab, icon1, "")
        self.FSM_model_tab = QtWidgets.QWidget()
        self.FSM_model_tab.setObjectName("FSM_model_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.FSM_model_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 80, 621, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.FSM_model_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.FSM_model_label.setObjectName("FSM_model_label")
        self.verticalLayout_11.addWidget(self.FSM_model_label)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem12)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.FSM_model_condition_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.FSM_model_condition_label.setObjectName("FSM_model_condition_label")
        self.horizontalLayout_24.addWidget(self.FSM_model_condition_label)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.representation_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.representation_label.setObjectName("representation_label")
        self.horizontalLayout_25.addWidget(self.representation_label)
        self.representation_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.representation_combobox.sizePolicy().hasHeightForWidth())
        self.representation_combobox.setSizePolicy(sizePolicy)
        self.representation_combobox.setObjectName("representation_combobox")
        self.representation_combobox.addItem("")
        self.representation_combobox.addItem("")
        self.representation_combobox.addItem("")
        self.horizontalLayout_25.addWidget(self.representation_combobox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.type_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.type_label.setObjectName("type_label")
        self.horizontalLayout_26.addWidget(self.type_label)
        self.type_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_combobox.sizePolicy().hasHeightForWidth())
        self.type_combobox.setSizePolicy(sizePolicy)
        self.type_combobox.setObjectName("type_combobox")
        self.type_combobox.addItem("")
        self.type_combobox.addItem("")
        self.horizontalLayout_26.addWidget(self.type_combobox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizon_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.horizon_label.setObjectName("horizon_label")
        self.horizontalLayout_27.addWidget(self.horizon_label)
        self.horizon_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.horizon_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horizon_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.horizon_lineEdit.setObjectName("horizon_lineEdit")
        self.horizontalLayout_27.addWidget(self.horizon_lineEdit)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.filter_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout_28.addWidget(self.filter_label)
        self.filter_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_combobox.sizePolicy().hasHeightForWidth())
        self.filter_combobox.setSizePolicy(sizePolicy)
        self.filter_combobox.setObjectName("filter_combobox")
        self.filter_combobox.addItem("")
        self.filter_combobox.addItem("")
        self.filter_combobox.addItem("")
        self.filter_combobox.addItem("")
        self.horizontalLayout_28.addWidget(self.filter_combobox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_28)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem14)
        self.next_push_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_push_4.sizePolicy().hasHeightForWidth())
        self.next_push_4.setSizePolicy(sizePolicy)
        self.next_push_4.setObjectName("next_push_4")
        self.verticalLayout_11.addWidget(self.next_push_4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/fsm_model.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.FSM_model_tab, icon2, "")
        self.machine_path_tab = QtWidgets.QWidget()
        self.machine_path_tab.setObjectName("machine_path_tab")
        self.layoutWidget_3 = QtWidgets.QWidget(self.machine_path_tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 80, 611, 375))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BOB_WOW_path_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.BOB_WOW_path_label.setObjectName("BOB_WOW_path_label")
        self.verticalLayout_3.addWidget(self.BOB_WOW_path_label)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LOT_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.LOT_label.setObjectName("LOT_label")
        self.horizontalLayout_4.addWidget(self.LOT_label)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.LOT_criteria_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.LOT_criteria_label.setObjectName("LOT_criteria_label")
        self.horizontalLayout_4.addWidget(self.LOT_criteria_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mean_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.mean_label.setObjectName("mean_label")
        self.horizontalLayout_5.addWidget(self.mean_label)
        self.mean_combobox = QtWidgets.QComboBox(self.layoutWidget_3)
        self.mean_combobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mean_combobox.sizePolicy().hasHeightForWidth())
        self.mean_combobox.setSizePolicy(sizePolicy)
        self.mean_combobox.setMinimumSize(QtCore.QSize(300, 0))
        self.mean_combobox.setMouseTracking(False)
        self.mean_combobox.setObjectName("mean_combobox")
        self.mean_combobox.addItem("")
        self.mean_combobox.addItem("")
        self.mean_combobox.addItem("")
        self.horizontalLayout_5.addWidget(self.mean_combobox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.mean_BOB_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.mean_BOB_label.setObjectName("mean_BOB_label")
        self.horizontalLayout_12.addWidget(self.mean_BOB_label)
        self.mean_BOB_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mean_BOB_lineEdit.setEnabled(False)
        self.mean_BOB_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mean_BOB_lineEdit.setObjectName("mean_BOB_lineEdit")
        self.horizontalLayout_12.addWidget(self.mean_BOB_lineEdit)
        self.mean_WOW_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.mean_WOW_label.setObjectName("mean_WOW_label")
        self.horizontalLayout_12.addWidget(self.mean_WOW_label)
        self.mean_WOW_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mean_WOW_lineEdit.setEnabled(False)
        self.mean_WOW_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mean_WOW_lineEdit.setObjectName("mean_WOW_lineEdit")
        self.horizontalLayout_12.addWidget(self.mean_WOW_lineEdit)
        self.lot_convert_push = QtWidgets.QPushButton(self.layoutWidget_3)
        self.lot_convert_push.setEnabled(False)
        self.lot_convert_push.setObjectName("lot_convert_push")
        self.horizontalLayout_12.addWidget(self.lot_convert_push)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.BOB_mean = QtWidgets.QLabel(self.layoutWidget_3)
        self.BOB_mean.setObjectName("BOB_mean")
        self.horizontalLayout_12.addWidget(self.BOB_mean)
        self.WOW_mean = QtWidgets.QLabel(self.layoutWidget_3)
        self.WOW_mean.setObjectName("WOW_mean")
        self.horizontalLayout_12.addWidget(self.WOW_mean)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.std_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.std_label.setObjectName("std_label")
        self.horizontalLayout_6.addWidget(self.std_label)
        self.std_combobox = QtWidgets.QComboBox(self.layoutWidget_3)
        self.std_combobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.std_combobox.sizePolicy().hasHeightForWidth())
        self.std_combobox.setSizePolicy(sizePolicy)
        self.std_combobox.setMinimumSize(QtCore.QSize(300, 0))
        self.std_combobox.setObjectName("std_combobox")
        self.std_combobox.addItem("")
        self.std_combobox.addItem("")
        self.std_combobox.addItem("")
        self.horizontalLayout_6.addWidget(self.std_combobox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem18)
        self.std_Under_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.std_Under_label.setObjectName("std_Under_label")
        self.horizontalLayout_19.addWidget(self.std_Under_label)
        self.std_Under_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.std_Under_lineEdit.setEnabled(False)
        self.std_Under_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.std_Under_lineEdit.setObjectName("std_Under_lineEdit")
        self.horizontalLayout_19.addWidget(self.std_Under_lineEdit)
        self.std_Over_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.std_Over_label.setObjectName("std_Over_label")
        self.horizontalLayout_19.addWidget(self.std_Over_label)
        self.std_Over_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.std_Over_lineEdit.setEnabled(False)
        self.std_Over_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.std_Over_lineEdit.setObjectName("std_Over_lineEdit")
        self.horizontalLayout_19.addWidget(self.std_Over_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Wafer_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.Wafer_label.setObjectName("Wafer_label")
        self.horizontalLayout_10.addWidget(self.Wafer_label)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem20)
        self.Wafer_criteria_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.Wafer_criteria_label.setObjectName("Wafer_criteria_label")
        self.horizontalLayout_10.addWidget(self.Wafer_criteria_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.value_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.value_label.setObjectName("value_label")
        self.horizontalLayout_11.addWidget(self.value_label)
        self.value_criterion_combobox = QtWidgets.QComboBox(self.layoutWidget_3)
        self.value_criterion_combobox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_criterion_combobox.sizePolicy().hasHeightForWidth())
        self.value_criterion_combobox.setSizePolicy(sizePolicy)
        self.value_criterion_combobox.setMinimumSize(QtCore.QSize(300, 0))
        self.value_criterion_combobox.setObjectName("value_criterion_combobox")
        self.value_criterion_combobox.addItem("")
        self.value_criterion_combobox.addItem("")
        self.value_criterion_combobox.addItem("")
        self.horizontalLayout_11.addWidget(self.value_criterion_combobox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem21)
        self.value_BOB_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.value_BOB_label.setObjectName("value_BOB_label")
        self.horizontalLayout_20.addWidget(self.value_BOB_label)
        self.value_BOB_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.value_BOB_lineEdit.setEnabled(False)
        self.value_BOB_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.value_BOB_lineEdit.setObjectName("value_BOB_lineEdit")
        self.horizontalLayout_20.addWidget(self.value_BOB_lineEdit)
        self.value_WOW_label = QtWidgets.QLabel(self.layoutWidget_3)
        self.value_WOW_label.setObjectName("value_WOW_label")
        self.horizontalLayout_20.addWidget(self.value_WOW_label)
        self.value_WOW_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.value_WOW_lineEdit.setEnabled(False)
        self.value_WOW_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.value_WOW_lineEdit.setObjectName("value_WOW_lineEdit")
        self.horizontalLayout_20.addWidget(self.value_WOW_lineEdit)
        self.convert_push = QtWidgets.QPushButton(self.layoutWidget_3)
        self.convert_push.setEnabled(False)
        self.convert_push.setObjectName("convert_push")
        self.horizontalLayout_20.addWidget(self.convert_push)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_20.addWidget(self.label_4)
        self.BOB_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.BOB_value.setObjectName("BOB_value")
        self.horizontalLayout_20.addWidget(self.BOB_value)
        self.WOW_value = QtWidgets.QLabel(self.layoutWidget_3)
        self.WOW_value.setObjectName("WOW_value")
        self.horizontalLayout_20.addWidget(self.WOW_value)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem22)
        self.next_push_5 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_push_5.sizePolicy().hasHeightForWidth())
        self.next_push_5.setSizePolicy(sizePolicy)
        self.next_push_5.setObjectName("next_push_5")
        self.verticalLayout_3.addWidget(self.next_push_5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/path.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.machine_path_tab, icon3, "")
        self.high_low_machine_tab = QtWidgets.QWidget()
        self.high_low_machine_tab.setObjectName("high_low_machine_tab")
        self.layoutWidget_4 = QtWidgets.QWidget(self.high_low_machine_tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(60, 110, 601, 217))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.high_low_machine_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.high_low_machine_label.setObjectName("high_low_machine_label")
        self.verticalLayout_6.addWidget(self.high_low_machine_label)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem23)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.analysis_list_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.analysis_list_label.setObjectName("analysis_list_label")
        self.horizontalLayout_13.addWidget(self.analysis_list_label)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem24)
        self.analysis_check_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.analysis_check_label.setObjectName("analysis_check_label")
        self.horizontalLayout_13.addWidget(self.analysis_check_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.statistical_analysis_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.statistical_analysis_label.setObjectName("statistical_analysis_label")
        self.horizontalLayout_14.addWidget(self.statistical_analysis_label)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem25)
        self.statistical_analysis_check = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.statistical_analysis_check.setText("")
        self.statistical_analysis_check.setChecked(False)
        self.statistical_analysis_check.setObjectName("statistical_analysis_check")
        self.horizontalLayout_14.addWidget(self.statistical_analysis_check)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.user_defined_analysis_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.user_defined_analysis_label.setObjectName("user_defined_analysis_label")
        self.horizontalLayout_15.addWidget(self.user_defined_analysis_label)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem26)
        self.user_defined_analysis_check = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.user_defined_analysis_check.setText("")
        self.user_defined_analysis_check.setObjectName("user_defined_analysis_check")
        self.horizontalLayout_15.addWidget(self.user_defined_analysis_check)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.and_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.and_label.setObjectName("and_label")
        self.horizontalLayout_16.addWidget(self.and_label)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem27)
        self.and_check = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.and_check.setText("")
        self.and_check.setObjectName("and_check")
        self.horizontalLayout_16.addWidget(self.and_check)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem28)
        self.next_push_6 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_push_6.sizePolicy().hasHeightForWidth())
        self.next_push_6.setSizePolicy(sizePolicy)
        self.next_push_6.setObjectName("next_push_6")
        self.verticalLayout_6.addWidget(self.next_push_6)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/machine_classification.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.high_low_machine_tab, icon4, "")
        self.machine_path_simplify_label = QtWidgets.QWidget()
        self.machine_path_simplify_label.setObjectName("machine_path_simplify_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.machine_path_simplify_label)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 90, 541, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem29)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.dummy_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.dummy_label.setObjectName("dummy_label")
        self.horizontalLayout_17.addWidget(self.dummy_label)
        self.dummy_combobox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dummy_combobox.sizePolicy().hasHeightForWidth())
        self.dummy_combobox.setSizePolicy(sizePolicy)
        self.dummy_combobox.setObjectName("dummy_combobox")
        self.dummy_combobox.addItem("")
        self.dummy_combobox.addItem("")
        self.dummy_combobox.addItem("")
        self.horizontalLayout_17.addWidget(self.dummy_combobox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem30)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.visualization_push = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.visualization_push.setObjectName("visualization_push")
        self.horizontalLayout_18.addWidget(self.visualization_push)
        self.verticalLayout_12.addLayout(self.horizontalLayout_18)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/simplification.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.machine_path_simplify_label, icon5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.input_label.setText(_translate("Form", "데이터 입력"))
        self.input_lineEdit.setPlaceholderText(_translate("Form", "데이터명을 입력해 주세요."))
        self.file_push.setText(_translate("Form", "파일 첨부"))
        self.filename_lineEdit.setPlaceholderText(_translate("Form", "첨부된 파일명"))
        self.user_label.setText(_translate("Form", "사용자"))
        self.username_lineEdit.setPlaceholderText(_translate("Form", "사용자 이름"))
        self.userinfo_lineEdit.setPlaceholderText(_translate("Form", "기타 정보를 입력하세요"))
        self.analysis_label.setText(_translate("Form", "분석 구분 선택"))
        self.analysis_combobox.setItemText(0, _translate("Form", "Wafer-based Analysis"))
        self.analysis_combobox.setItemText(1, _translate("Form", "Lot-based Analysis"))
        self.analysis_combobox.setItemText(2, _translate("Form", "Wafer-based Analysis on specific Lot"))
        self.next_push.setText(_translate("Form", "다음 단계로"))
        self.data_preprocess_label_1.setText(_translate("Form", "데이터 전처리 (1)"))
        self.Incomplete_checkbox.setText(_translate("Form", "시작부터 종료까지의 전체 STEP이 기록되지 않은 LOT/Wafer 제외 "))
        self.start_end_label.setText(_translate("Form", "START STEP/ END STEP                  "))
        self.start_lineEdit.setPlaceholderText(_translate("Form", "Start Step(e.g. STEP001)"))
        self.end_lineEdit.setPlaceholderText(_translate("Form", "End Step(e.g. STEP075)"))
        self.minimum_wafer_checkbox.setText(_translate("Form", "  LOT 내 최소 Wafer 수 제한"))
        self.max_label.setText(_translate("Form", "최소 Wafer 수                                                                         "))
        self.min_num_lineEdit.setText(_translate("Form", "23"))
        self.min_num_lineEdit.setPlaceholderText(_translate("Form", "minimum_counts"))
        self.next_push_2.setText(_translate("Form", "다음 단계로"))
        self.data_preprocess_label_2.setText(_translate("Form", "데이터 전처리 (2)"))
        self.start_end_optimal_period_check.setText(_translate("Form", "분석 시작/종료 STEP 기준 최적 기간 추천"))
        self.step_criterion_label.setText(_translate("Form", "STEP 기준 설정"))
        self.step_criterion_lineEdit.setText(_translate("Form", "80"))
        self.label.setText(_translate("Form", "%"))
        self.period_checkbox.setText(_translate("Form", "각 STEP 기간 추출"))
        self.period_lineEdit.setPlaceholderText(_translate("Form", "e.g. S001, 2016-11-19, 2016-12-03; S075, 2017-02-14, 2017-02-28;"))
        self.main_checkbox.setText(_translate("Form", "분석 대상 STEP 추출"))
        self.main_lineEdit.setPlaceholderText(_translate("Form", "e.g. S038; S039; S040; S041;"))
        self.next_push_3.setText(_translate("Form", "다음 단계로"))
        self.FSM_model_label.setText(_translate("Form", "FSM model 도출"))
        self.FSM_model_condition_label.setText(_translate("Form", "FSM model 항목 내역"))
        self.representation_label.setText(_translate("Form", "Representation"))
        self.representation_combobox.setItemText(0, _translate("Form", "Sequence"))
        self.representation_combobox.setItemText(1, _translate("Form", "Set"))
        self.representation_combobox.setItemText(2, _translate("Form", "Multi Set"))
        self.type_label.setText(_translate("Form", "Type"))
        self.type_combobox.setItemText(0, _translate("Form", "Prefix"))
        self.type_combobox.setItemText(1, _translate("Form", "Postfix"))
        self.horizon_label.setText(_translate("Form", "Horizon"))
        self.horizon_lineEdit.setText(_translate("Form", "1"))
        self.horizon_lineEdit.setPlaceholderText(_translate("Form", "Integer"))
        self.filter_label.setText(_translate("Form", "Filter"))
        self.filter_combobox.setItemText(0, _translate("Form", "Option"))
        self.filter_combobox.setItemText(1, _translate("Form", "Sequence"))
        self.filter_combobox.setItemText(2, _translate("Form", "Set"))
        self.filter_combobox.setItemText(3, _translate("Form", "Multi Set"))
        self.next_push_4.setText(_translate("Form", "다음 단계로"))
        self.BOB_WOW_path_label.setText(_translate("Form", "BOB/WOW 설비 Path 도출"))
        self.LOT_label.setText(_translate("Form", "LOT 평가 내역                                                                                                   "))
        self.LOT_criteria_label.setText(_translate("Form", "평가 기준"))
        self.mean_label.setText(_translate("Form", "수율 평균"))
        self.mean_combobox.setItemText(0, _translate("Form", "Relative Ratio"))
        self.mean_combobox.setItemText(1, _translate("Form", "Absolute Value"))
        self.mean_combobox.setItemText(2, _translate("Form", "Rank-based"))
        self.mean_BOB_label.setText(_translate("Form", "BOB"))
        self.mean_WOW_label.setText(_translate("Form", "WOW"))
        self.lot_convert_push.setText(_translate("Form", "Convert"))
        self.label_5.setText(_translate("Form", "Absolute value:"))
        self.BOB_mean.setText(_translate("Form", "BOB"))
        self.WOW_mean.setText(_translate("Form", "WOW"))
        self.std_label.setText(_translate("Form", "수율 표준편차"))
        self.std_combobox.setItemText(0, _translate("Form", "Relative Ratio"))
        self.std_combobox.setItemText(1, _translate("Form", "Absolute Value"))
        self.std_combobox.setItemText(2, _translate("Form", "Rank-based"))
        self.std_Under_label.setText(_translate("Form", "Under"))
        self.std_Over_label.setText(_translate("Form", "Over"))
        self.Wafer_label.setText(_translate("Form", "Wafer 평가 내역                                                                                                   "))
        self.Wafer_criteria_label.setText(_translate("Form", "평가 기준"))
        self.value_label.setText(_translate("Form", "수율"))
        self.value_criterion_combobox.setItemText(0, _translate("Form", "Relative Ratio"))
        self.value_criterion_combobox.setItemText(1, _translate("Form", "Absolute Value"))
        self.value_criterion_combobox.setItemText(2, _translate("Form", "Rank-based"))
        self.value_BOB_label.setText(_translate("Form", "BOB"))
        self.value_WOW_label.setText(_translate("Form", "WOW"))
        self.convert_push.setText(_translate("Form", "Convert"))
        self.label_4.setText(_translate("Form", "Absolute value:"))
        self.BOB_value.setText(_translate("Form", "BOB"))
        self.WOW_value.setText(_translate("Form", "WOW"))
        self.next_push_5.setText(_translate("Form", "다음 단계로"))
        self.high_low_machine_label.setText(_translate("Form", "고수율/저수율 설비 도출"))
        self.analysis_list_label.setText(_translate("Form", "고수율/저수율 설비 분석 내역"))
        self.analysis_check_label.setText(_translate("Form", "수행 여부"))
        self.statistical_analysis_label.setText(_translate("Form", "통계 분석"))
        self.user_defined_analysis_label.setText(_translate("Form", "사용자 지정 수율 분석"))
        self.and_label.setText(_translate("Form", "두 분석 결과에 대해 \'AND\' 조건 적용"))
        self.next_push_6.setText(_translate("Form", "다음 단계로"))
        self.label_23.setText(_translate("Form", "BOB/WOW 설비 Path 단순화"))
        self.dummy_label.setText(_translate("Form", "더미화 조건 선택"))
        self.dummy_combobox.setItemText(0, _translate("Form", "STEP 내 모든 설비 더미화"))
        self.dummy_combobox.setItemText(1, _translate("Form", "이전 STEP의 모든 설비의 성과 속성이 같은 설비 더미화"))
        self.dummy_combobox.setItemText(2, _translate("Form", "이후 STEP의 모든 설비의 성과 속성이 같은 설비 더미화"))
        self.visualization_push.setText(_translate("Form", "FSM 모델 시각화"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

