# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stat_parameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 344)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 351, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.value_criterion_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.value_criterion_label.setObjectName("value_criterion_label")
        self.verticalLayout.addWidget(self.value_criterion_label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.KS_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.KS_label.setObjectName("KS_label")
        self.horizontalLayout.addWidget(self.KS_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.KS_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.KS_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.KS_alpha_lineEdit.setObjectName("KS_alpha_lineEdit")
        self.horizontalLayout.addWidget(self.KS_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ANOVA_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ANOVA_label.setObjectName("ANOVA_label")
        self.horizontalLayout_2.addWidget(self.ANOVA_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.ANOVA_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.ANOVA_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ANOVA_alpha_lineEdit.setObjectName("ANOVA_alpha_lineEdit")
        self.horizontalLayout_2.addWidget(self.ANOVA_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.KRUSKAL_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.KRUSKAL_label.setObjectName("KRUSKAL_label")
        self.horizontalLayout_3.addWidget(self.KRUSKAL_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.KRUSKAL_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.KRUSKAL_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.KRUSKAL_alpha_lineEdit.setObjectName("KRUSKAL_alpha_lineEdit")
        self.horizontalLayout_3.addWidget(self.KRUSKAL_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LC_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.LC_label.setObjectName("LC_label")
        self.horizontalLayout_4.addWidget(self.LC_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.LC_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LC_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LC_alpha_lineEdit.setObjectName("LC_alpha_lineEdit")
        self.horizontalLayout_4.addWidget(self.LC_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.NLC_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.NLC_label.setObjectName("NLC_label")
        self.horizontalLayout_7.addWidget(self.NLC_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.NLC_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.NLC_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.NLC_alpha_lineEdit.setObjectName("NLC_alpha_lineEdit")
        self.horizontalLayout_7.addWidget(self.NLC_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.MT_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MT_label.setObjectName("MT_label")
        self.horizontalLayout_5.addWidget(self.MT_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.MT_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.MT_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.MT_alpha_lineEdit.setObjectName("MT_alpha_lineEdit")
        self.horizontalLayout_5.addWidget(self.MT_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.UT_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.UT_label.setObjectName("UT_label")
        self.horizontalLayout_9.addWidget(self.UT_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.UT_alpha_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.UT_alpha_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.UT_alpha_lineEdit.setObjectName("UT_alpha_lineEdit")
        self.horizontalLayout_9.addWidget(self.UT_alpha_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.stat_push = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.stat_push.setObjectName("stat_push")
        self.verticalLayout.addWidget(self.stat_push)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.value_criterion_label.setText(_translate("Dialog", "통계 분석 Parameter 설정"))
        self.KS_label.setText(_translate("Dialog", "KS"))
        self.KS_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.KS_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.ANOVA_label.setText(_translate("Dialog", "ANOVA"))
        self.ANOVA_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.ANOVA_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.KRUSKAL_label.setText(_translate("Dialog", "KRUSKAL"))
        self.KRUSKAL_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.KRUSKAL_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.LC_label.setText(_translate("Dialog", "Linear Contrast"))
        self.LC_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.LC_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.NLC_label.setText(_translate("Dialog", "Nonparametric Linear Contrast"))
        self.NLC_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.NLC_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.MT_label.setText(_translate("Dialog", "Multiple T-test"))
        self.MT_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.MT_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.UT_label.setText(_translate("Dialog", "Multiple U-test"))
        self.UT_alpha_lineEdit.setText(_translate("Dialog", "0.05"))
        self.UT_alpha_lineEdit.setPlaceholderText(_translate("Dialog", "Alpha"))
        self.stat_push.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

