# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_defined_analysis_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 351, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UDA_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.UDA_label.setObjectName("UDA_label")
        self.verticalLayout.addWidget(self.UDA_label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BOB_avg_lavel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.BOB_avg_lavel.setObjectName("BOB_avg_lavel")
        self.horizontalLayout.addWidget(self.BOB_avg_lavel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.BOB_avg_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.BOB_avg_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.BOB_avg_lineEdit.setText("")
        self.BOB_avg_lineEdit.setPlaceholderText("")
        self.BOB_avg_lineEdit.setObjectName("BOB_avg_lineEdit")
        self.horizontalLayout.addWidget(self.BOB_avg_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WOW_avg_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.WOW_avg_label.setObjectName("WOW_avg_label")
        self.horizontalLayout_2.addWidget(self.WOW_avg_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.WOW_avg_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.WOW_avg_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.WOW_avg_lineEdit.setText("")
        self.WOW_avg_lineEdit.setPlaceholderText("")
        self.WOW_avg_lineEdit.setObjectName("WOW_avg_lineEdit")
        self.horizontalLayout_2.addWidget(self.WOW_avg_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BOB_prop_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.BOB_prop_label.setObjectName("BOB_prop_label")
        self.horizontalLayout_3.addWidget(self.BOB_prop_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.BOB_prop_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.BOB_prop_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.BOB_prop_lineEdit.setText("")
        self.BOB_prop_lineEdit.setPlaceholderText("")
        self.BOB_prop_lineEdit.setObjectName("BOB_prop_lineEdit")
        self.horizontalLayout_3.addWidget(self.BOB_prop_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.WOW_prop_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.WOW_prop_label.setObjectName("WOW_prop_label")
        self.horizontalLayout_4.addWidget(self.WOW_prop_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.WOW_prop_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.WOW_prop_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.WOW_prop_lineEdit.setPlaceholderText("")
        self.WOW_prop_lineEdit.setObjectName("WOW_prop_lineEdit")
        self.horizontalLayout_4.addWidget(self.WOW_prop_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.machine_weight_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.machine_weight_label.setObjectName("machine_weight_label")
        self.horizontalLayout_7.addWidget(self.machine_weight_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.machine_weight_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.machine_weight_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.machine_weight_lineEdit.setPlaceholderText("")
        self.machine_weight_lineEdit.setObjectName("machine_weight_lineEdit")
        self.horizontalLayout_7.addWidget(self.machine_weight_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.step_weight_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.step_weight_label.setObjectName("step_weight_label")
        self.horizontalLayout_5.addWidget(self.step_weight_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.step_weight_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.step_weight_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.step_weight_lineEdit.setPlaceholderText("")
        self.step_weight_lineEdit.setObjectName("step_weight_lineEdit")
        self.horizontalLayout_5.addWidget(self.step_weight_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mode_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mode_label.setObjectName("mode_label")
        self.horizontalLayout_9.addWidget(self.mode_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.mode_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.mode_lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mode_lineEdit.setObjectName("mode_lineEdit")
        self.horizontalLayout_9.addWidget(self.mode_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.UDA_push = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.UDA_push.setObjectName("UDA_push")
        self.verticalLayout.addWidget(self.UDA_push)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.UDA_label.setText(_translate("Dialog", "사용자 지정 기준 분석 Parameter 설정"))
        self.BOB_avg_lavel.setText(_translate("Dialog", "BOB 평균"))
        self.WOW_avg_label.setText(_translate("Dialog", "WOW 평균"))
        self.BOB_prop_label.setText(_translate("Dialog", "BOB 비율"))
        self.WOW_prop_label.setText(_translate("Dialog", "WOW 비율"))
        self.machine_weight_label.setText(_translate("Dialog", "machine_weight"))
        self.machine_weight_lineEdit.setText(_translate("Dialog", "0.5"))
        self.step_weight_label.setText(_translate("Dialog", "step_weight"))
        self.step_weight_lineEdit.setText(_translate("Dialog", "0.5"))
        self.mode_label.setText(_translate("Dialog", "mode"))
        self.mode_lineEdit.setPlaceholderText(_translate("Dialog", "and/or"))
        self.UDA_push.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

